#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ABP_Clamthulu_Eye_01

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function ABP_Clamthulu_Eye_01.ABP_Clamthulu_Eye_01_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ABP_Clamthulu_Eye_01_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};

// Function ABP_Clamthulu_Eye_01.ABP_Clamthulu_Eye_01_C.ExecuteUbergraph_ABP_Clamthulu_Eye_01
// 0x0004 (0x0004 - 0x0000)
struct ABP_Clamthulu_Eye_01_C_ExecuteUbergraph_ABP_Clamthulu_Eye_01 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

