#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ALI_Player_Character_Movement

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ALI_Player_Character_Movement.ALI_Player_Character_Movement_C
// 0x0000 (0x0000 - 0x0000)
class IALI_Player_Character_Movement_C final
{
public:
	void The_Movement(struct FPoseLink* The_Movement_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ALI_Player_Character_Movement_C">();
	}
	static class IALI_Player_Character_Movement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IALI_Player_Character_Movement_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

}

