#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_AngelCombCore_Ripple_NotifyState

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AngelCombCore_Ripple_NotifyState.BP_AngelCombCore_Ripple_NotifyState_C
// 0x344A2FD0 (0x344A3000 - 0x0030)
class alignas(0x344A3000) UBP_AngelCombCore_Ripple_NotifyState_C final : public UAnimNotifyState
{
public:
	class UCurveFloat*                            Intensity_Curve;                                   // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	bool Received_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, const struct FAnimNotifyEventReference& EventReference) const;
	bool Received_NotifyTick(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float FrameDeltaTime, const struct FAnimNotifyEventReference& EventReference) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AngelCombCore_Ripple_NotifyState_C">();
	}
	static class UBP_AngelCombCore_Ripple_NotifyState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AngelCombCore_Ripple_NotifyState_C>();
	}
};

}

