#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_AxumBioprintCulture

#include "Basic.hpp"

#include "BP_BasePickupItem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AxumBioprintCulture.BP_AxumBioprintCulture_C
// 0x344A2C40 (0x344A3000 - 0x03C0)
class alignas(0x344A3000) ABP_AxumBioprintCulture_C final : public ABP_BasePickupItem_C
{
public:
	class UUWEAssetDataComponent*                 UWEAssetData;                                      // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USN2BaseScannerStationSignalComponent*  SN2BaseScannerStationSignal;                       // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEAbilitySystemComponent*             UWEAbilitySystem;                                  // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AxumBioprintCulture_C">();
	}
	static class ABP_AxumBioprintCulture_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AxumBioprintCulture_C>();
	}
};

}

