#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_ButtonStyle_OptionArrow

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ButtonStyle_OptionArrow.BP_ButtonStyle_OptionArrow_C
// 0x0000 (0x0710 - 0x0710)
class UBP_ButtonStyle_OptionArrow_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ButtonStyle_OptionArrow_C">();
	}
	static class UBP_ButtonStyle_OptionArrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ButtonStyle_OptionArrow_C>();
	}
};

}

