#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_BaseModule_PlatformCenter_01a

#include "Basic.hpp"

#include "BP_Bases_KitPieces_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BaseModule_PlatformCenter_01a.BP_BaseModule_PlatformCenter_01a_C
// 0x00C2 (0x344A30C2 - 0x344A3000)
class alignas(0x344A30C2) ABP_BaseModule_PlatformCenter_01a_C final : public ABP_Bases_KitPieces_Parent_C
{
public:
	class UStaticMeshComponent*                   SM_Foundation_Edge_OutsideCorner_A3_StaticMeshComponent1; // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Foundation_Edge_OutsideCorner_A3_StaticMeshComponent0; // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        SharedRoot;                                        // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BaseModule_PlatformCenter_01a_C">();
	}
	static class ABP_BaseModule_PlatformCenter_01a_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BaseModule_PlatformCenter_01a_C>();
	}
};

}

