#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_ButtonStyle_PaperDollCircle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ButtonStyle_PaperDollCircle.BP_ButtonStyle_PaperDollCircle_C
// 0x0000 (0x0710 - 0x0710)
class UBP_ButtonStyle_PaperDollCircle_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ButtonStyle_PaperDollCircle_C">();
	}
	static class UBP_ButtonStyle_PaperDollCircle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ButtonStyle_PaperDollCircle_C>();
	}
};

}

