#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_ButtonStyle_CheatListEntry

#include "Basic.hpp"

#include "BP_ButtonStyle_Common_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ButtonStyle_CheatListEntry.BP_ButtonStyle_CheatListEntry_C
// 0x0000 (0x0710 - 0x0710)
class UBP_ButtonStyle_CheatListEntry_C final : public UBP_ButtonStyle_Common_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ButtonStyle_CheatListEntry_C">();
	}
	static class UBP_ButtonStyle_CheatListEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ButtonStyle_CheatListEntry_C>();
	}
};

}

