#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_CoralCabbage_02b

#include "Basic.hpp"

#include "BP_CoralCabbage_01a_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CoralCabbage_02b.BP_CoralCabbage_02b_C
// 0x0000 (0x344A3000 - 0x344A3000)
class ABP_CoralCabbage_02b_C final : public ABP_CoralCabbage_01a_C
{
public:
	uint8                                         Pad_2D1[0x7];                                      // 0x02D1(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UPointLightComponent*                   PointLight;                                        // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CoralCabbage_02b_C">();
	}
	static class ABP_CoralCabbage_02b_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CoralCabbage_02b_C>();
	}
};

}

