#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_ElusiveLeviathanAuraCameraShake

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ElusiveLeviathanAuraCameraShake.BP_ElusiveLeviathanAuraCameraShake_C
// 0x0000 (0x00E0 - 0x00E0)
class UBP_ElusiveLeviathanAuraCameraShake_C final : public UDefaultCameraShakeBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ElusiveLeviathanAuraCameraShake_C">();
	}
	static class UBP_ElusiveLeviathanAuraCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ElusiveLeviathanAuraCameraShake_C>();
	}
};

}

