#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_FetchPlayerRebreatherEquipped

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FetchPlayerRebreatherEquipped.BP_FetchPlayerRebreatherEquipped_C
// 0x0000 (0x0030 - 0x0030)
class UBP_FetchPlayerRebreatherEquipped_C final : public UUWECueParamFetchFunction
{
public:
	float FetchParam(const struct FGameplayCueParameters& CueParams, const struct FUWEEffectParam& EffectParam, const class AActor* Target);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FetchPlayerRebreatherEquipped_C">();
	}
	static class UBP_FetchPlayerRebreatherEquipped_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FetchPlayerRebreatherEquipped_C>();
	}
};

}

