#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Greeble_RoofFan_Fan_A

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Greeble_RoofFan_Fan_A.BP_Greeble_RoofFan_Fan_A_C
// 0x344A2D50 (0x344A3000 - 0x02B0)
class alignas(0x344A3000) ABP_Greeble_RoofFan_Fan_A_C final : public AActor
{
public:
	class URotatingMovementComponent*             RotatingMovement;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UpdatePowerState(bool IsPowered);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Greeble_RoofFan_Fan_A_C">();
	}
	static class ABP_Greeble_RoofFan_Fan_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Greeble_RoofFan_Fan_A_C>();
	}
};

}

