#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Greeble_RoofAntenna_C_Radar

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Greeble_RoofAntenna_C_Radar.BP_Greeble_RoofAntenna_C_Radar_C.UpdatePowerState
// 0x0001 (0x0001 - 0x0000)
struct BP_Greeble_RoofAntenna_C_Radar_C_UpdatePowerState final
{
public:
	bool                                          Powered;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

