#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Greeble_RoofFan_Fan_A

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Greeble_RoofFan_Fan_A.BP_Greeble_RoofFan_Fan_A_C.UpdatePowerState
// 0x0001 (0x0001 - 0x0000)
struct BP_Greeble_RoofFan_Fan_A_C_UpdatePowerState final
{
public:
	bool                                          IsPowered;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

