#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_GameplayCueStatics

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GameplayCueStatics.BP_GameplayCueStatics_C
// 0x0000 (0x0028 - 0x0028)
class UBP_GameplayCueStatics_C final : public UBlueprintFunctionLibrary
{
public:
	static void MakePlayerDamageReactionGCParams(class AActor* Target, const struct FGameplayCueParameters& Params_0, class UObject* __WorldContext, struct FF_PlayerDamageReactionCueParams* DamageParams);
	static void MakeScanningGCParams(const struct FGameplayCueParameters& Params_0, class UObject* __WorldContext, struct FF_ScanningCueParams* ScanningParams, bool* Success_);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GameplayCueStatics_C">();
	}
	static class UBP_GameplayCueStatics_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GameplayCueStatics_C>();
	}
};

}

