#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_GraveyardPlayerStart_BlackBoxesPOI

#include "Basic.hpp"

#include "BP_GraveyardPlayerStart_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GraveyardPlayerStart_BlackBoxesPOI.BP_GraveyardPlayerStart_BlackBoxesPOI_C
// 0x0000 (0x344A3000 - 0x344A3000)
class ABP_GraveyardPlayerStart_BlackBoxesPOI_C final : public ABP_GraveyardPlayerStart_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GraveyardPlayerStart_BlackBoxesPOI_C">();
	}
	static class ABP_GraveyardPlayerStart_BlackBoxesPOI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GraveyardPlayerStart_BlackBoxesPOI_C>();
	}
};

}

