#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_HatchCorridorPreview

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HatchCorridorPreview.BP_HatchCorridorPreview_C
// 0x344A2D50 (0x344A3000 - 0x02B0)
class alignas(0x344A3000) ABP_HatchCorridorPreview_C final : public AActor
{
public:
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HatchCorridorPreview_C">();
	}
	static class ABP_HatchCorridorPreview_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HatchCorridorPreview_C>();
	}
};

}

