#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Lighting_Alterra_03

#include "Basic.hpp"

#include "BP_Lighting_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Lighting_Alterra_03.BP_Lighting_Alterra_03_C
// 0x0000 (0x344A3000 - 0x344A3000)
class ABP_Lighting_Alterra_03_C final : public ABP_Lighting_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Lighting_Alterra_03_C">();
	}
	static class ABP_Lighting_Alterra_03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Lighting_Alterra_03_C>();
	}
};

}

