#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_NewsfeedLinkDecorator

#include "Basic.hpp"

#include "UWECommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NewsfeedLinkDecorator.BP_NewsfeedLinkDecorator_C
// 0x0000 (0x06C0 - 0x06C0)
class UBP_NewsfeedLinkDecorator_C final : public UUWERichTextBlockLinkDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NewsfeedLinkDecorator_C">();
	}
	static class UBP_NewsfeedLinkDecorator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NewsfeedLinkDecorator_C>();
	}
};

}

