#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_NecroleiEgg_Item

#include "Basic.hpp"

#include "UWEInventory_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NecroleiEgg_Item.BP_NecroleiEgg_Item_C
// 0x344A2C48 (0x344A3000 - 0x03B8)
class alignas(0x344A3000) ABP_NecroleiEgg_Item_C final : public AUWEBaseItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUWEAssetDataComponent*                 UWEAssetData;                                      // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_NecroleiEgg_Item(int32 EntryPoint);
	bool IsPickupDisabled(class AActor* FromActor, const struct FHitResult& HitResult);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NecroleiEgg_Item_C">();
	}
	static class ABP_NecroleiEgg_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NecroleiEgg_Item_C>();
	}
};

}

