#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_PlantAirSac_01a

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlantAirSac_01a.BP_PlantAirSac_01a_C
// 0x344A2D50 (0x344A3000 - 0x02B0)
class alignas(0x344A3000) ABP_PlantAirSac_01a_C final : public AActor
{
public:
	class UUWEAssetDataComponent*                 UWEAssetData;                                      // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_PlantAirSac_01a;                                // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PlantAirSac_01a_C">();
	}
	static class ABP_PlantAirSac_01a_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlantAirSac_01a_C>();
	}
};

}

