#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_Resource_GatewayCrystal_01a

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BasePickupItem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Resource_GatewayCrystal_01a.BP_Resource_GatewayCrystal_01a_C
// 0x344A2C40 (0x344A3000 - 0x03C0)
class alignas(0x344A3000) ABP_Resource_GatewayCrystal_01a_C final : public ABP_BasePickupItem_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Resource_GatewayCrystal_01a_C;   // 0x03C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUWEAbilitySystemComponent*             UWEAbilitySystem;                                  // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UUWEAssetDataComponent*                 UWEAssetData;                                      // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          IsReadyToBePickedUp;                               // 0x03D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void EventReceived_2DF8BE674DCB2C71C1FB0ABFADD9460E(const struct FGameplayEventData& Payload);
	void ExecuteUbergraph_BP_Resource_GatewayCrystal_01a(int32 EntryPoint);
	bool IsPickupDisabled(class AActor* FromActor, const struct FHitResult& HitResult);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Resource_GatewayCrystal_01a_C">();
	}
	static class ABP_Resource_GatewayCrystal_01a_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Resource_GatewayCrystal_01a_C>();
	}
};

}

