#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_ResourceHit_CameraShake

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ResourceHit_CameraShake.BP_ResourceHit_CameraShake_C
// 0x0000 (0x00E0 - 0x00E0)
class UBP_ResourceHit_CameraShake_C final : public UDefaultCameraShakeBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ResourceHit_CameraShake_C">();
	}
	static class UBP_ResourceHit_CameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ResourceHit_CameraShake_C>();
	}
};

}

