#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_ResourceNode_PearlClamthuluPrototype

#include "Basic.hpp"

#include "BP_DynamicResourceParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ResourceNode_PearlClamthuluPrototype.BP_ResourceNode_PearlClamthuluPrototype_C
// 0x0000 (0x344A3000 - 0x344A3000)
class ABP_ResourceNode_PearlClamthuluPrototype_C final : public ABP_DynamicResourceParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ResourceNode_PearlClamthuluPrototype_C">();
	}
	static class ABP_ResourceNode_PearlClamthuluPrototype_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ResourceNode_PearlClamthuluPrototype_C>();
	}
};

}

