#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_SN2WorldGameMode

#include "Basic.hpp"

#include "Subnautica2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SN2WorldGameMode.BP_SN2WorldGameMode_C
// 0x344A2B68 (0x344A3000 - 0x0498)
class alignas(0x344A3000) ABP_SN2WorldGameMode_C : public ASN2WorldGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	class UClass* GetDefaultPawnClassForController(class AController* InController);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SN2WorldGameMode_C">();
	}
	static class ABP_SN2WorldGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SN2WorldGameMode_C>();
	}
};

}

