#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_SplineTentacleBlight

#include "Basic.hpp"

#include "BP_SplineTentacle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SplineTentacleBlight.BP_SplineTentacleBlight_C
// 0x0000 (0x344A3000 - 0x344A3000)
class ABP_SplineTentacleBlight_C final : public ABP_SplineTentacle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SplineTentacleBlight_C">();
	}
	static class ABP_SplineTentacleBlight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SplineTentacleBlight_C>();
	}
};

}

