#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_TextStyle_HeadingDustyTeal_18px

#include "Basic.hpp"

#include "BP_TextStyle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TextStyle_HeadingDustyTeal_18px.BP_TextStyle_HeadingDustyTeal_18px_C
// 0x0000 (0x0190 - 0x0190)
class UBP_TextStyle_HeadingDustyTeal_18px_C final : public UBP_TextStyle_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TextStyle_HeadingDustyTeal_18px_C">();
	}
	static class UBP_TextStyle_HeadingDustyTeal_18px_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TextStyle_HeadingDustyTeal_18px_C>();
	}
};

}

