#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_TextStyle_RedStroke

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TextStyle_RedStroke.BP_TextStyle_RedStroke_C
// 0x0000 (0x0190 - 0x0190)
class UBP_TextStyle_RedStroke_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TextStyle_RedStroke_C">();
	}
	static class UBP_TextStyle_RedStroke_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TextStyle_RedStroke_C>();
	}
};

}

