#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_ThermalPlantHead_Scan

#include "Basic.hpp"

#include "BP_Scannable_BaseClass_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ThermalPlantHead_Scan.BP_ThermalPlantHead_Scan_C
// 0x0000 (0x344A3000 - 0x344A3000)
class ABP_ThermalPlantHead_Scan_C final : public ABP_Scannable_BaseClass_C
{
public:
	uint8                                         Pad_2D9[0x7];                                      // 0x02D9(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	class UStaticMeshComponent*                   BaseMesh4;                                         // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BaseMesh2;                                         // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ThermalPlantHead_Scan_C">();
	}
	static class ABP_ThermalPlantHead_Scan_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ThermalPlantHead_Scan_C>();
	}
};

}

