#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_TestStoryGoalTrigger

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TestStoryGoalTrigger.BP_TestStoryGoalTrigger_C
// 0x344A2D48 (0x344A3000 - 0x02B8)
#pragma pack(push, 0x1)
class alignas(0x344A3000) ABP_TestStoryGoalTrigger_C : public ATriggerBox
{
public:
	class UUWEStoryGoalTriggerComponent*          UWEStoryGoalTrigger;                               // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cube;                                              // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TestStoryGoalTrigger_C">();
	}
	static class ABP_TestStoryGoalTrigger_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TestStoryGoalTrigger_C>();
	}
};
#pragma pack(pop)

}

