#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_TemperatureHelpers

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TemperatureHelpers.BP_TemperatureHelpers_C
// 0x0000 (0x0028 - 0x0028)
class UBP_TemperatureHelpers_C final : public UBlueprintFunctionLibrary
{
public:
	static void ComputeTemperatureToAddAtPoint(const struct FVector& Location, class UObject* __WorldContext, double* Temperature, bool* HasTemperature);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TemperatureHelpers_C">();
	}
	static class UBP_TemperatureHelpers_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TemperatureHelpers_C>();
	}
};

}

