#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_TwinEels_FollowerIsAttached

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TwinEels_FollowerIsAttached.BP_TwinEels_FollowerIsAttached_C
// 0x0000 (0x00A0 - 0x00A0)
class UBP_TwinEels_FollowerIsAttached_C final : public UBTDecorator_BlueprintBase
{
public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TwinEels_FollowerIsAttached_C">();
	}
	static class UBP_TwinEels_FollowerIsAttached_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TwinEels_FollowerIsAttached_C>();
	}
};

}

