#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_WorldPopSpawnedQuartz

#include "Basic.hpp"

#include "UWEWorldPopulation2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WorldPopSpawnedQuartz.BP_WorldPopSpawnedQuartz_C
// 0x0000 (0x0348 - 0x0348)
class ABP_WorldPopSpawnedQuartz_C final : public AUWEWorldPopResourceBaseActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_WorldPopSpawnedQuartz_C">();
	}
	static class ABP_WorldPopSpawnedQuartz_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WorldPopSpawnedQuartz_C>();
	}
};

}

