#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPC_PlayerStateDeathPingComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_PlayerStateDeathPingComponent.BPC_PlayerStateDeathPingComponent_C
// 0x344A2F40 (0x344A3000 - 0x00C0)
class alignas(0x344A3000) UBPC_PlayerStateDeathPingComponent_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGuid                                  LastActivePing;                                    // 0x00C8(0x0010)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUWESaveHandle*                         SaveHandle;                                        // 0x00D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AddActivePing(const struct FGuid& PingID);
	void ExecuteUbergraph_BPC_PlayerStateDeathPingComponent(int32 EntryPoint);
	void GetLastPingLocation(bool* HasPing, struct FVector* Location);
	void OnPostDeserialize();
	void OnPostSerialize();
	void OnPreDeserialize();
	void OnPreSerialize();
	void RemoveActivePing(const struct FGuid& PingID);
	void SetHandle(class UUWESaveHandle* InSaveHandle);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPC_PlayerStateDeathPingComponent_C">();
	}
	static class UBPC_PlayerStateDeathPingComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_PlayerStateDeathPingComponent_C>();
	}
};

}

