#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPC_ClamthuluEyeSkeletalMesh

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_ClamthuluEyeSkeletalMesh.BPC_ClamthuluEyeSkeletalMesh_C
// 0x344A2008 (0x344A3000 - 0x0FF8)
class alignas(0x344A3000) UBPC_ClamthuluEyeSkeletalMesh_C final : public USkeletalMeshComponent
{
public:
	uint8                                         Pad_FF8[0x8];                                      // 0x0FF8(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1000(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	double                                        LookAtDuration;                                    // 0x1008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CurrentLookAtTime;                                 // 0x1010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPC_ClamthuluEyeSkeletalMesh(int32 EntryPoint);
	void LookAtPlayerEnd();
	void LookAtPlayerStart();
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void TryGetClamthuluEyeAnimInstance(class UABP_Clamthulu_Eye_01_C** ClamthuluEyeAnimInstance);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPC_ClamthuluEyeSkeletalMesh_C">();
	}
	static class UBPC_ClamthuluEyeSkeletalMesh_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_ClamthuluEyeSkeletalMesh_C>();
	}
};

}

