#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPFL_PlayerStartUtils

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPFL_PlayerStartUtils.BPFL_PlayerStartUtils_C
// 0x0000 (0x0028 - 0x0028)
class UBPFL_PlayerStartUtils_C final : public UBlueprintFunctionLibrary
{
public:
	static void InitializeArrayOfItemsToSpawn(const TArray<TSoftObjectPtr<class UUWEItemType>>& TargetArrayForCosts, TArray<class UUWECraftingRecipe*>& ListOfBasePieces, int32 BonusTitaniumForSculptsCount, class UObject* __WorldContext, TArray<TSoftObjectPtr<class UUWEItemType>>* InitializedArray);
	static void SpawnLockerAtNextOpenSpot(int32 NumLockersSpawned, double DistBetweenLockersCM, class AActor* PlayerActorToSpawnNear, class UObject* __WorldContext, class ABP_FloatingLocker_Deprecated_C** LockerSpawned);

	void SpawnLockersWithSuppliesForYourBase(class AActor* PlayerActorSelfReference, TArray<class UUWECraftingRecipe*>& ListOfBasePieces, int32 BonusTitaniumForSculptsCount, class UObject* __WorldContext);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPFL_PlayerStartUtils_C">();
	}
	static class UBPFL_PlayerStartUtils_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPFL_PlayerStartUtils_C>();
	}
};

}

