#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: EFieldActivationType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EFieldActivationType.EFieldActivationType
// NumValues: 0x0005
enum class EFieldActivationType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator2                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	EFieldActivationType_MAX                 = 4,
};

}

