#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: F_Lighting

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct F_Lighting.F_Lighting
// 0x0020 (0x0020 - 0x0000)
struct FF_Lighting final
{
public:
	struct FLinearColor                           SkyLuminanceFactor_2_012BDA34422567B7DAF4119B398E4E02; // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MieScattering_8_6C6E9A92497B64E7D301E6B6005D73B7;  // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MieAbsorption_9_84B584334F2D39609F8478B04899C86E;  // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

