#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_AI_CoralCrab_Hide

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_AI_CoralCrab_Hide.GA_AI_CoralCrab_Hide_C
// 0x0008 (0x0540 - 0x0538)
class UGA_AI_CoralCrab_Hide_C final : public UUWEGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0538(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void CheckForObstaclesUnder(bool* ObstacleFound);
	void CheckForObstaclesUnderAndKill();
	void ExecuteUbergraph_GA_AI_CoralCrab_Hide(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnCompleted_AC95A73246C2173FBE43EA95B7F6CDBC();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_AI_CoralCrab_Hide_C">();
	}
	static class UGA_AI_CoralCrab_Hide_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_AI_CoralCrab_Hide_C>();
	}
};

}

