#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_AI_BlightParasite_Bite

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_AI_BlightParasite_Bite.GA_AI_BlightParasite_Bite_C
// 0x0008 (0x0540 - 0x0538)
class UGA_AI_BlightParasite_Bite_C final : public UUWEGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0538(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_AI_BlightParasite_Bite(int32 EntryPoint);
	void K2_ActivateAbility();
	void OnCompleted_C98F891546C9843AD599829AA56ECB3F();
	void OnNotifyBegin_15AE1A73473D03B1A196119BA767DDD8();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_AI_BlightParasite_Bite_C">();
	}
	static class UGA_AI_BlightParasite_Bite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_AI_BlightParasite_Bite_C>();
	}
};

}

