#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_PressurizedLungs_BioAbility

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEBiomods_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_PressurizedLungs_BioAbility.GA_PressurizedLungs_BioAbility_C
// 0x0008 (0x0540 - 0x0538)
class UGA_PressurizedLungs_BioAbility_C final : public UUWEBioAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0538(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_PressurizedLungs_BioAbility(int32 EntryPoint);
	void InvalidHandle_E4E37BBB47A71230808642B541423E72(const struct FGameplayEffectRemovalInfo& GameplayEffectRemovalInfo);
	void K2_ActivateAbility();
	void OnRemoved_E4E37BBB47A71230808642B541423E72(const struct FGameplayEffectRemovalInfo& GameplayEffectRemovalInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_PressurizedLungs_BioAbility_C">();
	}
	static class UGA_PressurizedLungs_BioAbility_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_PressurizedLungs_BioAbility_C>();
	}
};

}

