#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_TadpoleLights

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_TadpoleLights.GA_TadpoleLights_C
// 0x0010 (0x0548 - 0x0538)
class UGA_TadpoleLights_C final : public UUWEGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0538(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FActiveGameplayEffectHandle            StimulusEffect;                                    // 0x0540(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_TadpoleLights(int32 EntryPoint);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnChassChanged(class AActor* Chassis);
	void OnPress_ACA1615D49E2901DD84630B487589038(float TimeWaited);
	void OnTagRequirementsFailed_F307CEEB4445C2AE81C729B00B310196();
	void PlayLightsOffCue();
	void PlayLightsOnCue();
	void UpdateLightCue();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_TadpoleLights_C">();
	}
	static class UGA_TadpoleLights_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_TadpoleLights_C>();
	}
};

}

