#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GameplayCameras

#include "Basic.hpp"

#include "GameplayCameras_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function GameplayCameras.BlueprintCameraEvaluationDataFunctionLibrary.BlendCameraEvaluationData
// 0x0038 (0x0038 - 0x0000)
struct BlueprintCameraEvaluationDataFunctionLibrary_BlendCameraEvaluationData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      FromCameraData;                                    // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FBlueprintCameraEvaluationDataRef      ToCameraData;                                      // 0x0018(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         Factor;                                            // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraEvaluationDataFunctionLibrary.GetCameraPose
// 0x00A0 (0x00A0 - 0x0000)
struct BlueprintCameraEvaluationDataFunctionLibrary_GetCameraPose final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x0018(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraEvaluationDataFunctionLibrary.MakeCameraEvaluationData
// 0x0018 (0x0018 - 0x0000)
struct BlueprintCameraEvaluationDataFunctionLibrary_MakeCameraEvaluationData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraEvaluationDataFunctionLibrary.SetCameraPose
// 0x00A0 (0x00A0 - 0x0000)
struct BlueprintCameraEvaluationDataFunctionLibrary_SetCameraPose final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0018(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraEvaluationDataFunctionLibrary.SetDefaultCameraRigParameters
// 0x0020 (0x0020 - 0x0000)
struct BlueprintCameraEvaluationDataFunctionLibrary_SetDefaultCameraRigParameters final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	const class UCameraRigAsset*                  CameraRig;                                         // 0x0018(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetBooleanCameraVariable
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetBooleanCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UBooleanCameraVariable*                 Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetDoubleCameraVariable
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetDoubleCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UDoubleCameraVariable*                  Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	double                                        ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetFloatCameraVariable
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetFloatCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UFloatCameraVariable*                   Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0020(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetInteger32CameraVariable
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetInteger32CameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UInteger32CameraVariable*               Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0020(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetRotatorCameraVariable
// 0x0038 (0x0038 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetRotatorCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class URotator3dCameraVariable*               Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               ReturnValue;                                       // 0x0020(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetTransformCameraVariable
// 0x0080 (0x0080 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetTransformCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UTransform3dCameraVariable*             Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTransform                             ReturnValue;                                       // 0x0020(0x0060)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetVector2CameraVariable
// 0x0030 (0x0030 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetVector2CameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UVector2dCameraVariable*                Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              ReturnValue;                                       // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetVector3CameraVariable
// 0x0038 (0x0038 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetVector3CameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UVector3dCameraVariable*                Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ReturnValue;                                       // 0x0020(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.GetVector4CameraVariable
// 0x0040 (0x0040 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_GetVector4CameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UVector4dCameraVariable*                Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector4                               ReturnValue;                                       // 0x0020(0x0020)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetBooleanCameraVariable
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetBooleanCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UBooleanCameraVariable*                 Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Value;                                             // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetDoubleCameraVariable
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetDoubleCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UDoubleCameraVariable*                  Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	double                                        Value;                                             // 0x0020(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetFloatCameraVariable
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetFloatCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UFloatCameraVariable*                   Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Value;                                             // 0x0020(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetInteger32CameraVariable
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetInteger32CameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UInteger32CameraVariable*               Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Value;                                             // 0x0020(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetRotatorCameraVariable
// 0x0038 (0x0038 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetRotatorCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class URotator3dCameraVariable*               Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Value;                                             // 0x0020(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetTransformCameraVariable
// 0x0080 (0x0080 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetTransformCameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UTransform3dCameraVariable*             Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FTransform                             Value;                                             // 0x0020(0x0060)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetVector2CameraVariable
// 0x0030 (0x0030 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetVector2CameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UVector2dCameraVariable*                Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              Value;                                             // 0x0020(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetVector3CameraVariable
// 0x0038 (0x0038 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetVector3CameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UVector3dCameraVariable*                Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Value;                                             // 0x0020(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraVariableTableFunctionLibrary.SetVector4CameraVariable
// 0x0040 (0x0040 - 0x0000)
struct BlueprintCameraVariableTableFunctionLibrary_SetVector4CameraVariable final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UVector4dCameraVariable*                Variable;                                          // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector4                               Value;                                             // 0x0020(0x0020)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.GetClassData
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_GetClassData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UClass*                                 ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.GetEnumData
// 0x0030 (0x0030 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_GetEnumData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	const class UEnum*                            EnumType;                                          // 0x0020(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         ReturnValue;                                       // 0x0028(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.GetNameData
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_GetNameData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ReturnValue;                                       // 0x001C(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.GetObjectData
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_GetObjectData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.GetStringData
// 0x0030 (0x0030 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_GetStringData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class FString                                 ReturnValue;                                       // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.GetStructData
// 0x0038 (0x0038 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_GetStructData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	const class UScriptStruct*                    DataStructType;                                    // 0x0020(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FInstancedStruct                       ReturnValue;                                       // 0x0028(0x0010)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.SetClassData
// 0x0030 (0x0030 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_SetClassData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UClass*                                 Data;                                              // 0x0020(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0028(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.SetEnumData
// 0x0030 (0x0030 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_SetEnumData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	const class UEnum*                            EnumType;                                          // 0x0020(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Data;                                              // 0x0028(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0029(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.SetNameData
// 0x0028 (0x0028 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_SetNameData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Data;                                              // 0x001C(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0024(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.SetObjectData
// 0x0030 (0x0030 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_SetObjectData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                Data;                                              // 0x0020(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0028(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.SetStringData
// 0x0038 (0x0038 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_SetStringData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class FString                                 Data;                                              // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraContextDataTableFunctionLibrary.SetStructData
// 0x0038 (0x0038 - 0x0000)
struct BlueprintCameraContextDataTableFunctionLibrary_SetStructData final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FCameraContextDataID                   DataID;                                            // 0x0018(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FInstancedStruct                       Data;                                              // 0x0020(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.CameraRigInstanceFunctions.IsValid
// 0x000C (0x000C - 0x0000)
struct CameraRigInstanceFunctions_IsValid final
{
public:
	struct FCameraRigInstanceID                   InstanceId;                                        // 0x0000(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayCameraParameterSetterComponent.OnActorBeginOverlap
// 0x0010 (0x0010 - 0x0000)
struct GameplayCameraParameterSetterComponent_OnActorBeginOverlap final
{
public:
	class AActor*                                 OverlappedActor;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraParameterSetterComponent.OnActorEndOverlap
// 0x0010 (0x0010 - 0x0000)
struct GameplayCameraParameterSetterComponent_OnActorEndOverlap final
{
public:
	class AActor*                                 OverlappedActor;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraParameterSetterComponent.StopParameterSetters
// 0x0001 (0x0001 - 0x0000)
struct GameplayCameraParameterSetterComponent_StopParameterSetters final
{
public:
	bool                                          bImmediately;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCamerasPlayerCameraManager.StartGlobalCameraModifierRig
// 0x0018 (0x0018 - 0x0000)
struct GameplayCamerasPlayerCameraManager_StartGlobalCameraModifierRig final
{
public:
	const class UCameraRigAsset*                  CameraRig;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         OrderKey;                                          // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCameraRigInstanceID                   ReturnValue;                                       // 0x000C(0x0008)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayCamerasPlayerCameraManager.StartVisualCameraModifierRig
// 0x0018 (0x0018 - 0x0000)
struct GameplayCamerasPlayerCameraManager_StartVisualCameraModifierRig final
{
public:
	const class UCameraRigAsset*                  CameraRig;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         OrderKey;                                          // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCameraRigInstanceID                   ReturnValue;                                       // 0x000C(0x0008)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayCamerasPlayerCameraManager.StealPlayerController
// 0x0008 (0x0008 - 0x0000)
struct GameplayCamerasPlayerCameraManager_StealPlayerController final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCamerasPlayerCameraManager.StopCameraModifierRig
// 0x000C (0x000C - 0x0000)
struct GameplayCamerasPlayerCameraManager_StopCameraModifierRig final
{
public:
	struct FCameraRigInstanceID                   InstanceId;                                        // 0x0000(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImmediately;                                      // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.ActivateCameraDirector
// 0x0010 (0x0010 - 0x0000)
struct BlueprintCameraDirectorEvaluator_ActivateCameraDirector final
{
public:
	class UObject*                                EvaluationContextOwner;                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBlueprintCameraDirectorActivateParams Params_0;                                          // 0x0008(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.ActivateCameraRig
// 0x0010 (0x0010 - 0x0000)
struct BlueprintCameraDirectorEvaluator_ActivateCameraRig final
{
public:
	class UCameraRigAsset*                        CameraRig;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceNewInstance;                                 // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.ActivateCameraRigViaProxy
// 0x0010 (0x0010 - 0x0000)
struct BlueprintCameraDirectorEvaluator_ActivateCameraRigViaProxy final
{
public:
	class UCameraRigProxyAsset*                   CameraRigProxy;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceNewInstance;                                 // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.ActivatePersistentBaseCameraRig
// 0x0008 (0x0008 - 0x0000)
struct BlueprintCameraDirectorEvaluator_ActivatePersistentBaseCameraRig final
{
public:
	class UCameraRigAsset*                        CameraRigPrefab;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.ActivatePersistentGlobalCameraRig
// 0x0008 (0x0008 - 0x0000)
struct BlueprintCameraDirectorEvaluator_ActivatePersistentGlobalCameraRig final
{
public:
	class UCameraRigAsset*                        CameraRigPrefab;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.ActivatePersistentVisualCameraRig
// 0x0008 (0x0008 - 0x0000)
struct BlueprintCameraDirectorEvaluator_ActivatePersistentVisualCameraRig final
{
public:
	class UCameraRigAsset*                        CameraRigPrefab;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.AddChildEvaluationContext
// 0x0010 (0x0010 - 0x0000)
struct BlueprintCameraDirectorEvaluator_AddChildEvaluationContext final
{
public:
	class UObject*                                ChildEvaluationContextOwner;                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.DeactivateCameraDirector
// 0x0010 (0x0010 - 0x0000)
struct BlueprintCameraDirectorEvaluator_DeactivateCameraDirector final
{
public:
	class UObject*                                EvaluationContextOwner;                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBlueprintCameraDirectorDeactivateParams Params_0;                                        // 0x0008(0x0008)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.DeactivatePersistentBaseCameraRig
// 0x0008 (0x0008 - 0x0000)
struct BlueprintCameraDirectorEvaluator_DeactivatePersistentBaseCameraRig final
{
public:
	class UCameraRigAsset*                        CameraRigPrefab;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.DeactivatePersistentGlobalCameraRig
// 0x0008 (0x0008 - 0x0000)
struct BlueprintCameraDirectorEvaluator_DeactivatePersistentGlobalCameraRig final
{
public:
	class UCameraRigAsset*                        CameraRigPrefab;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.DeactivatePersistentVisualCameraRig
// 0x0008 (0x0008 - 0x0000)
struct BlueprintCameraDirectorEvaluator_DeactivatePersistentVisualCameraRig final
{
public:
	class UCameraRigAsset*                        CameraRigPrefab;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.RemoveChildEvaluationContext
// 0x0018 (0x0018 - 0x0000)
struct BlueprintCameraDirectorEvaluator_RemoveChildEvaluationContext final
{
public:
	class UObject*                                ChildEvaluationContextOwner;                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ChildSlotName;                                     // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.RunCameraDirector
// 0x0020 (0x0020 - 0x0000)
struct BlueprintCameraDirectorEvaluator_RunCameraDirector final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	class UObject*                                EvaluationContextOwner;                            // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBlueprintCameraDirectorEvaluationParams Params_0;                                        // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.RunChildCameraDirector
// 0x0010 (0x0010 - 0x0000)
struct BlueprintCameraDirectorEvaluator_RunChildCameraDirector final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ChildSlotName;                                     // 0x0004(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.FindEvaluationContextOwnerActor
// 0x0010 (0x0010 - 0x0000)
struct BlueprintCameraDirectorEvaluator_FindEvaluationContextOwnerActor final
{
public:
	TSubclassOf<class AActor>                     ActorClass;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.GetConditionalContextResult
// 0x0020 (0x0020 - 0x0000)
struct BlueprintCameraDirectorEvaluator_GetConditionalContextResult final
{
public:
	ECameraEvaluationDataCondition                Condition;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FBlueprintCameraEvaluationDataRef      ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraDirectorEvaluator.GetInitialContextResult
// 0x0018 (0x0018 - 0x0000)
struct BlueprintCameraDirectorEvaluator_GetInitialContextResult final
{
public:
	struct FBlueprintCameraEvaluationDataRef      ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.ActivateCameraRigFunctions.ActivatePersistentBaseCameraRig
// 0x0018 (0x0018 - 0x0000)
struct ActivateCameraRigFunctions_ActivatePersistentBaseCameraRig final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APlayerController*                      PlayerController;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCameraRigAsset*                        CameraRig;                                         // 0x0010(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.ActivateCameraRigFunctions.ActivatePersistentGlobalCameraRig
// 0x0018 (0x0018 - 0x0000)
struct ActivateCameraRigFunctions_ActivatePersistentGlobalCameraRig final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APlayerController*                      PlayerController;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCameraRigAsset*                        CameraRig;                                         // 0x0010(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.ActivateCameraRigFunctions.ActivatePersistentVisualCameraRig
// 0x0018 (0x0018 - 0x0000)
struct ActivateCameraRigFunctions_ActivatePersistentVisualCameraRig final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APlayerController*                      PlayerController;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCameraRigAsset*                        CameraRig;                                         // 0x0010(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetAimDir
// 0x00A0 (0x00A0 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetAimDir final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                ReturnValue;                                       // 0x0088(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetAimRay
// 0x00B8 (0x00B8 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetAimRay final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FRay                                   ReturnValue;                                       // 0x0088(0x0030)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetEffectiveFieldOfView
// 0x0090 (0x0090 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetEffectiveFieldOfView final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	double                                        ReturnValue;                                       // 0x0088(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetFieldOfView
// 0x0090 (0x0090 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetFieldOfView final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	double                                        ReturnValue;                                       // 0x0088(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetFocalLength
// 0x0090 (0x0090 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetFocalLength final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	double                                        ReturnValue;                                       // 0x0088(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetLocation
// 0x00A0 (0x00A0 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetLocation final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                ReturnValue;                                       // 0x0088(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetRotation
// 0x00A0 (0x00A0 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetRotation final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               ReturnValue;                                       // 0x0088(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetSensorAspectRatio
// 0x0090 (0x0090 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetSensorAspectRatio final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	double                                        ReturnValue;                                       // 0x0088(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetTarget
// 0x00A0 (0x00A0 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetTarget final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                ReturnValue;                                       // 0x0088(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetTargetAtDistance
// 0x00A8 (0x00A8 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetTargetAtDistance final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	double                                        TargetDistance;                                    // 0x0088(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ReturnValue;                                       // 0x0090(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetTargetDistance
// 0x0090 (0x0090 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetTargetDistance final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	double                                        ReturnValue;                                       // 0x0088(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.GetTransform
// 0x00F0 (0x00F0 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_GetTransform final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_88[0x8];                                       // 0x0088(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FTransform                             ReturnValue;                                       // 0x0090(0x0060)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.MakeCameraPoseFromCameraComponent
// 0x0090 (0x0090 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_MakeCameraPoseFromCameraComponent final
{
public:
	const class UCameraComponent*                 CameraComponent;                                   // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x0008(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.MakeCameraPoseFromCineCameraComponent
// 0x0090 (0x0090 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_MakeCameraPoseFromCineCameraComponent final
{
public:
	const class UCineCameraComponent*             CameraComponent;                                   // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x0008(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.SetFieldOfView
// 0x0118 (0x0118 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_SetFieldOfView final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	float                                         FieldOfView;                                       // 0x0088(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x0090(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.SetFocalLength
// 0x0118 (0x0118 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_SetFocalLength final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	float                                         FocalLength;                                       // 0x0088(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-8 ])
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x0090(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.SetLocation
// 0x0128 (0x0128 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_SetLocation final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                Location;                                          // 0x0088(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x00A0(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.SetRotation
// 0x0128 (0x0128 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_SetRotation final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               Rotation;                                          // 0x0088(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x00A0(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.SetTargetDistance
// 0x0118 (0x0118 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_SetTargetDistance final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	double                                        TargetDistance;                                    // 0x0088(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x0090(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraPoseFunctionLibrary.SetTransform
// 0x0180 (0x0180 - 0x0000)
struct BlueprintCameraPoseFunctionLibrary_SetTransform final
{
public:
	struct FBlueprintCameraPose                   CameraPose;                                        // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_88[0x8];                                       // 0x0088(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	struct FTransform                             Transform;                                         // 0x0090(0x0060)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x00F0(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_178[0x8];                                      // 0x0178(0x0008)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.CameraRigParameterInterop.GetCameraParameter
// 0x0030 (0x0030 - 0x0000)
struct CameraRigParameterInterop_GetCameraParameter final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UCameraRigAsset*                        CameraRig;                                         // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ParameterName;                                     // 0x0020(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0028(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.CameraRigParameterInterop.SetCameraParameter
// 0x0030 (0x0030 - 0x0000)
struct CameraRigParameterInterop_SetCameraParameter final
{
public:
	struct FBlueprintCameraEvaluationDataRef      CameraData;                                        // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class UCameraRigAsset*                        CameraRig;                                         // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ParameterName;                                     // 0x0020(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NewValue;                                          // 0x0028(0x0004)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.CameraRigParameterInteropLibrary.MakeLiteralLinearColor
// 0x0020 (0x0020 - 0x0000)
struct CameraRigParameterInteropLibrary_MakeLiteralLinearColor final
{
public:
	struct FLinearColor                           Value;                                             // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.CameraRigParameterInteropLibrary.MakeLiteralRotator
// 0x0030 (0x0030 - 0x0000)
struct CameraRigParameterInteropLibrary_MakeLiteralRotator final
{
public:
	struct FRotator                               Value;                                             // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               ReturnValue;                                       // 0x0018(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.CameraRigParameterInteropLibrary.MakeLiteralVector
// 0x0030 (0x0030 - 0x0000)
struct CameraRigParameterInteropLibrary_MakeLiteralVector final
{
public:
	struct FVector                                Value;                                             // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ReturnValue;                                       // 0x0018(0x0018)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.CameraRigParameterInteropLibrary.MakeLiteralVector2D
// 0x0020 (0x0020 - 0x0000)
struct CameraRigParameterInteropLibrary_MakeLiteralVector2D final
{
public:
	struct FVector2D                              Value;                                             // 0x0000(0x0010)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.CameraRigParameterInteropLibrary.MakeLiteralVector3f
// 0x0018 (0x0018 - 0x0000)
struct CameraRigParameterInteropLibrary_MakeLiteralVector3f final
{
public:
	struct FVector3f                              Value;                                             // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector3f                              ReturnValue;                                       // 0x000C(0x000C)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraActor.GetCameraComponent
// 0x0008 (0x0008 - 0x0000)
struct GameplayCameraActor_GetCameraComponent final
{
public:
	class UGameplayCameraComponent*               ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraComponentBase.ActivateCameraForPlayerController
// 0x0010 (0x0010 - 0x0000)
struct GameplayCameraComponentBase_ActivateCameraForPlayerController final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSetAsViewTarget;                                  // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGameplayCameraComponentActivationMode        ActivationMode;                                    // 0x0009(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayCameraComponentBase.ActivateCameraForPlayerIndex
// 0x0008 (0x0008 - 0x0000)
struct GameplayCameraComponentBase_ActivateCameraForPlayerIndex final
{
public:
	int32                                         PlayerIndex;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSetAsViewTarget;                                  // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EGameplayCameraComponentActivationMode        ActivationMode;                                    // 0x0005(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayCameraComponentBase.DeactivateCamera
// 0x0001 (0x0001 - 0x0000)
struct GameplayCameraComponentBase_DeactivateCamera final
{
public:
	bool                                          bImmediately;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraComponentBase.GetConditionalResult
// 0x0020 (0x0020 - 0x0000)
struct GameplayCameraComponentBase_GetConditionalResult final
{
public:
	ECameraEvaluationDataCondition                Condition;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-8 ])
	struct FBlueprintCameraEvaluationDataRef      ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraComponentBase.GetInitialResult
// 0x0018 (0x0018 - 0x0000)
struct GameplayCameraComponentBase_GetInitialResult final
{
public:
	struct FBlueprintCameraEvaluationDataRef      ReturnValue;                                       // 0x0000(0x0018)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraComponentBase.GetOutputCameraComponent
// 0x0008 (0x0008 - 0x0000)
struct GameplayCameraComponentBase_GetOutputCameraComponent final
{
public:
	class UCineCameraComponent*                   ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraRigActor.GetCameraRigComponent
// 0x0008 (0x0008 - 0x0000)
struct GameplayCameraRigActor_GetCameraRigComponent final
{
public:
	class UGameplayCameraRigComponent*            ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraSystemActor.GetCameraSystemComponent
// 0x0008 (0x0008 - 0x0000)
struct GameplayCameraSystemActor_GetCameraSystemComponent final
{
public:
	class UGameplayCameraSystemComponent*         ReturnValue;                                       // 0x0000(0x0008)(ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraSystemComponent.ActivateCameraSystemForPlayerController
// 0x0008 (0x0008 - 0x0000)
struct GameplayCameraSystemComponent_ActivateCameraSystemForPlayerController final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraSystemComponent.ActivateCameraSystemForPlayerIndex
// 0x0004 (0x0004 - 0x0000)
struct GameplayCameraSystemComponent_ActivateCameraSystemForPlayerIndex final
{
public:
	int32                                         PlayerIndex;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraSystemComponent.DeactivateCameraSystem
// 0x0008 (0x0008 - 0x0000)
struct GameplayCameraSystemComponent_DeactivateCameraSystem final
{
public:
	class AActor*                                 NextViewTarget;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayCameraSystemComponent.StartGlobalCameraModifierRig
// 0x0018 (0x0018 - 0x0000)
struct GameplayCameraSystemComponent_StartGlobalCameraModifierRig final
{
public:
	const class UCameraRigAsset*                  CameraRig;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         OrderKey;                                          // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCameraRigInstanceID                   ReturnValue;                                       // 0x000C(0x0008)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayCameraSystemComponent.StartVisualCameraModifierRig
// 0x0018 (0x0018 - 0x0000)
struct GameplayCameraSystemComponent_StartVisualCameraModifierRig final
{
public:
	const class UCameraRigAsset*                  CameraRig;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         OrderKey;                                          // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FCameraRigInstanceID                   ReturnValue;                                       // 0x000C(0x0008)(Parm, OutParm, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayCameraSystemComponent.StopCameraModifierRig
// 0x000C (0x000C - 0x0000)
struct GameplayCameraSystemComponent_StopCameraModifierRig final
{
public:
	struct FCameraRigInstanceID                   InstanceId;                                        // 0x0000(0x0008)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bImmediately;                                      // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayCameraSystemComponent.IsCameraSystemActiveForPlayController
// 0x0010 (0x0010 - 0x0000)
struct GameplayCameraSystemComponent_IsCameraSystemActiveForPlayController final
{
public:
	class APlayerController*                      PlayerController;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-8 ])
};

// Function GameplayCameras.GameplayControlRotationComponent.ActivateControlRotationManagementForPlayerController
// 0x0008 (0x0008 - 0x0000)
struct GameplayControlRotationComponent_ActivateControlRotationManagementForPlayerController final
{
public:
	class APlayerController*                      PlayerController_0;                                // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.GameplayControlRotationComponent.ActivateControlRotationManagementForPlayerIndex
// 0x0004 (0x0004 - 0x0000)
struct GameplayControlRotationComponent_ActivateControlRotationManagementForPlayerIndex final
{
public:
	int32                                         PlayerIndex;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraNodeEvaluator.SetCameraPose
// 0x0088 (0x0088 - 0x0000)
struct BlueprintCameraNodeEvaluator_SetCameraPose final
{
public:
	struct FBlueprintCameraPose                   InCameraPose;                                      // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraNodeEvaluator.SetCurrentCameraPose
// 0x0088 (0x0088 - 0x0000)
struct BlueprintCameraNodeEvaluator_SetCurrentCameraPose final
{
public:
	struct FBlueprintCameraPose                   CameraPose_0;                                      // 0x0000(0x0088)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraNodeEvaluator.TickCameraNode
// 0x0004 (0x0004 - 0x0000)
struct BlueprintCameraNodeEvaluator_TickCameraNode final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraNodeEvaluator.FindEvaluationContextOwnerActor
// 0x0010 (0x0010 - 0x0000)
struct BlueprintCameraNodeEvaluator_FindEvaluationContextOwnerActor final
{
public:
	TSubclassOf<class AActor>                     ActorClass;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraNodeEvaluator.GetCameraPose
// 0x0088 (0x0088 - 0x0000)
struct BlueprintCameraNodeEvaluator_GetCameraPose final
{
public:
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x0000(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraNodeEvaluator.GetCurrentCameraPose
// 0x0088 (0x0088 - 0x0000)
struct BlueprintCameraNodeEvaluator_GetCurrentCameraPose final
{
public:
	struct FBlueprintCameraPose                   ReturnValue;                                       // 0x0000(0x0088)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraNodeEvaluator.GetPlayerController
// 0x0008 (0x0008 - 0x0000)
struct BlueprintCameraNodeEvaluator_GetPlayerController final
{
public:
	class APlayerController*                      ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function GameplayCameras.BlueprintCameraNodeEvaluator.SetDefaultOwningCameraRigParameters
// 0x0018 (0x0018 - 0x0000)
struct BlueprintCameraNodeEvaluator_SetDefaultOwningCameraRigParameters final
{
public:
	struct FBlueprintCameraEvaluationDataRef      TargetCameraData;                                  // 0x0000(0x0018)(Parm, NativeAccessSpecifierPublic)
};

}

