#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_ActivateBuildMode

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_ActivateBuildMode.GC_ActivateBuildMode_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_ActivateBuildMode_C final : public UUWEGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_ActivateBuildMode_C">();
	}
	static class UGC_ActivateBuildMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_ActivateBuildMode_C>();
	}
};

}

