#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Clamthulu_Chewing_Loop

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Clamthulu_Chewing_Loop.GC_Clamthulu_Chewing_Loop_C
// 0x0000 (0x1738 - 0x1738)
class AGC_Clamthulu_Chewing_Loop_C final : public AUWEGameplayCueNotify_Looping
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Clamthulu_Chewing_Loop_C">();
	}
	static class AGC_Clamthulu_Chewing_Loop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Clamthulu_Chewing_Loop_C>();
	}
};

}

