#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Consume_Oxygen

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Consume_Oxygen.GC_Consume_Oxygen_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_Consume_Oxygen_C final : public UUWEGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Consume_Oxygen_C">();
	}
	static class UGC_Consume_Oxygen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Consume_Oxygen_C>();
	}
};

}

