#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Damage_Creature_Radiation

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Damage_Creature_Radiation.GC_Damage_Creature_Radiation_C
// 0x344A2740 (0x344A3000 - 0x08C0)
class alignas(0x344A3000) AGC_Damage_Creature_Radiation_C final : public AUWEGameplayCueNotify_BurstLatent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFXSystemComponent*                     pfx;                                               // 0x08C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GC_Damage_Creature_Radiation(int32 EntryPoint);
	void OnBurst(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Damage_Creature_Radiation_C">();
	}
	static class AGC_Damage_Creature_Radiation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Damage_Creature_Radiation_C>();
	}
};

}

