#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Damage_Player_Any

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Damage_Player_Any.GC_Damage_Player_Any_C
// 0x0008 (0x08C8 - 0x08C0)
class AGC_Damage_Player_Any_C final : public AUWEGameplayCueNotify_BurstLatent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GC_Damage_Player_Any(int32 EntryPoint);
	void OnBurst(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Damage_Player_Any_C">();
	}
	static class AGC_Damage_Player_Any_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Damage_Player_Any_C>();
	}
};

}

