#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Equip_Flares

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Equip_Flares.GC_Equip_Flares_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_Equip_Flares_C final : public UUWEGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Equip_Flares_C">();
	}
	static class UGC_Equip_Flares_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Equip_Flares_C>();
	}
};

}

