#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_EMTPointOxygenator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_EMTPointOxygenator.GC_EMTPointOxygenator_C
// 0x0008 (0x1740 - 0x1738)
class AGC_EMTPointOxygenator_C final : public AUWEGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1738(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GC_EMTPointOxygenator(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_EMTPointOxygenator_C">();
	}
	static class AGC_EMTPointOxygenator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_EMTPointOxygenator_C>();
	}
};

}

