#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_ElGeordie_DrainAttach

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_ElGeordie_DrainAttach.GC_ElGeordie_DrainAttach_C
// 0x0008 (0x1740 - 0x1738)
class AGC_ElGeordie_DrainAttach_C final : public AUWEGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1738(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GC_ElGeordie_DrainAttach(int32 EntryPoint);
	void OnLoopingStart(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);
	void OnRemoval(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_ElGeordie_DrainAttach_C">();
	}
	static class AGC_ElGeordie_DrainAttach_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_ElGeordie_DrainAttach_C>();
	}
};

}

