#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_HaulRig_CloseStorage

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_HaulRig_CloseStorage.GC_HaulRig_CloseStorage_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_HaulRig_CloseStorage_C final : public UUWEGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_HaulRig_CloseStorage_C">();
	}
	static class UGC_HaulRig_CloseStorage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_HaulRig_CloseStorage_C>();
	}
};

}

