#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_ImpactSound_prototype

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_ImpactSound_prototype.GC_ImpactSound_prototype_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_ImpactSound_prototype_C final : public UUWEGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_ImpactSound_prototype_C">();
	}
	static class UGC_ImpactSound_prototype_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_ImpactSound_prototype_C>();
	}
};

}

