#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Inoculator_Impact

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Inoculator_Impact.GC_Inoculator_Impact_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_Inoculator_Impact_C final : public UUWEGameplayCueNotify_Burst
{
public:
	void OnBurst(class AActor* Target, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Inoculator_Impact_C">();
	}
	static class UGC_Inoculator_Impact_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Inoculator_Impact_C>();
	}
};

}

