#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_LeakExteriorTrident

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_LeakExteriorTrident.GC_LeakExteriorTrident_C
// 0x0000 (0x1738 - 0x1738)
class AGC_LeakExteriorTrident_C final : public AUWEGameplayCueNotify_Looping
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_LeakExteriorTrident_C">();
	}
	static class AGC_LeakExteriorTrident_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_LeakExteriorTrident_C>();
	}
};

}

