#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_SwimFast_Start

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_SwimFast_Start.GC_SwimFast_Start_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_SwimFast_Start_C final : public UUWEGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_SwimFast_Start_C">();
	}
	static class UGC_SwimFast_Start_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_SwimFast_Start_C>();
	}
};

}

