#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_ScoutRayChassisDetach

#include "Basic.hpp"

#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_ScoutRayChassisDetach.GC_ScoutRayChassisDetach_C
// 0x0000 (0x04F0 - 0x04F0)
class UGC_ScoutRayChassisDetach_C final : public UUWEGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_ScoutRayChassisDetach_C">();
	}
	static class UGC_ScoutRayChassisDetach_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_ScoutRayChassisDetach_C>();
	}
};

}

