#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Tadpole_Active

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Tadpole_Active.GC_Tadpole_Active_C
// 0x344A18C8 (0x344A3000 - 0x1738)
class alignas(0x344A3000) AGC_Tadpole_Active_C final : public AUWEGameplayCueNotify_Looping
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1738(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPointLightComponent*                   EmergencyLight;                                    // 0x1740(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Target;                                            // 0x1748(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Parameters_Target_Attach_Component;                // 0x1750(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUWEAbilityAsync_WaitGameplayTagCountChanged* Async_Action;                                // 0x1758(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void CountChanged_CF6E24E54312950EB7D9F2BF57E1E8F8(const struct FGameplayTag& Tag, int32 NewCount, int32 OldCount);
	void ExecuteUbergraph_GC_Tadpole_Active(int32 EntryPoint);
	void OnLoopingStart(class AActor* Target_0, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);
	void OnRemoval(class AActor* Target_0, const struct FGameplayCueParameters& Parameters, const struct FUWEGameplayCueNotify_SpawnResult& SpawnResults);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Tadpole_Active_C">();
	}
	static class AGC_Tadpole_Active_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Tadpole_Active_C>();
	}
};

}

