#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GC_Weld

#include "Basic.hpp"

#include "UWEGameplayCues_structs.hpp"
#include "UWEGameplayCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Weld.GC_Weld_C
// 0x344A18C8 (0x344A3000 - 0x1738)
class alignas(0x344A3000) AGC_Weld_C final : public AUWEGameplayCueNotify_Looping
{
public:
	class AActor*                                 TargetActor;                                       // 0x1738(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ABP_RepairTool_C*                       As_BP_Welder;                                      // 0x1740(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FUWEGameplayCueNotify_SpawnResult      Spawn_Results;                                     // 0x1748(0x00F0)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_Weld_C">();
	}
	static class AGC_Weld_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_Weld_C>();
	}
};

}

