#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_ApplyAura

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_ApplyAura.GE_ApplyAura_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_ApplyAura_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_ApplyAura_C">();
	}
	static class UGE_ApplyAura_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_ApplyAura_C>();
	}
};

}

