#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_BiomodCooldown

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_BiomodCooldown.GE_BiomodCooldown_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_BiomodCooldown_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_BiomodCooldown_C">();
	}
	static class UGE_BiomodCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_BiomodCooldown_C>();
	}
};

}

