#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Creature_Flee

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Creature_Flee.GE_Creature_Flee_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_Creature_Flee_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Creature_Flee_C">();
	}
	static class UGE_Creature_Flee_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Creature_Flee_C>();
	}
};

}

