#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_DamageMultiplierSetByCaller

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_DamageMultiplierSetByCaller.GE_DamageMultiplierSetByCaller_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_DamageMultiplierSetByCaller_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_DamageMultiplierSetByCaller_C">();
	}
	static class UGE_DamageMultiplierSetByCaller_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_DamageMultiplierSetByCaller_C>();
	}
};

}

