#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_EnergyModifierSetByCaller

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_EnergyModifierSetByCaller.GE_EnergyModifierSetByCaller_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_EnergyModifierSetByCaller_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_EnergyModifierSetByCaller_C">();
	}
	static class UGE_EnergyModifierSetByCaller_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_EnergyModifierSetByCaller_C>();
	}
};

}

