#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_InfiniteStimulusSphere_Huge

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_InfiniteStimulusSphere_Huge.GE_InfiniteStimulusSphere_Huge_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_InfiniteStimulusSphere_Huge_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_InfiniteStimulusSphere_Huge_C">();
	}
	static class UGE_InfiniteStimulusSphere_Huge_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_InfiniteStimulusSphere_Huge_C>();
	}
};

}

