#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_LargeCreatureInitialAttributes

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_LargeCreatureInitialAttributes.GE_LargeCreatureInitialAttributes_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_LargeCreatureInitialAttributes_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_LargeCreatureInitialAttributes_C">();
	}
	static class UGE_LargeCreatureInitialAttributes_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_LargeCreatureInitialAttributes_C>();
	}
};

}

