#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_MaxHealthSetByCaller

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_MaxHealthSetByCaller.GE_MaxHealthSetByCaller_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_MaxHealthSetByCaller_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_MaxHealthSetByCaller_C">();
	}
	static class UGE_MaxHealthSetByCaller_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_MaxHealthSetByCaller_C>();
	}
};

}

