#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_OxygenReplenish_AirFissure

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_OxygenReplenish_AirFissure.GE_OxygenReplenish_AirFissure_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_OxygenReplenish_AirFissure_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_OxygenReplenish_AirFissure_C">();
	}
	static class UGE_OxygenReplenish_AirFissure_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_OxygenReplenish_AirFissure_C>();
	}
};

}

