#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Player_Blind

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Player_Blind.GE_Player_Blind_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_Player_Blind_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Player_Blind_C">();
	}
	static class UGE_Player_Blind_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Player_Blind_C>();
	}
};

}

