#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_PowerfulKicks_ExtremeTemp

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_PowerfulKicks_ExtremeTemp.GE_PowerfulKicks_ExtremeTemp_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_PowerfulKicks_ExtremeTemp_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_PowerfulKicks_ExtremeTemp_C">();
	}
	static class UGE_PowerfulKicks_ExtremeTemp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_PowerfulKicks_ExtremeTemp_C>();
	}
};

}

