#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_ParasiteRemoved

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_ParasiteRemoved.GE_ParasiteRemoved_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_ParasiteRemoved_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_ParasiteRemoved_C">();
	}
	static class UGE_ParasiteRemoved_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_ParasiteRemoved_C>();
	}
};

}

