#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_ReducedDashCooldown

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_ReducedDashCooldown.GE_ReducedDashCooldown_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_ReducedDashCooldown_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_ReducedDashCooldown_C">();
	}
	static class UGE_ReducedDashCooldown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_ReducedDashCooldown_C>();
	}
};

}

