#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Regeneration

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Regeneration.GE_Regeneration_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_Regeneration_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Regeneration_C">();
	}
	static class UGE_Regeneration_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Regeneration_C>();
	}
};

}

