#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_SymbioteCallStimulus

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_SymbioteCallStimulus.GE_SymbioteCallStimulus_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_SymbioteCallStimulus_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_SymbioteCallStimulus_C">();
	}
	static class UGE_SymbioteCallStimulus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SymbioteCallStimulus_C>();
	}
};

}

