#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_SetWalkSpeedSetByCaller

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_SetWalkSpeedSetByCaller.GE_SetWalkSpeedSetByCaller_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_SetWalkSpeedSetByCaller_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_SetWalkSpeedSetByCaller_C">();
	}
	static class UGE_SetWalkSpeedSetByCaller_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SetWalkSpeedSetByCaller_C>();
	}
};

}

