#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Suffocate

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Suffocate.GE_Suffocate_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_Suffocate_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Suffocate_C">();
	}
	static class UGE_Suffocate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Suffocate_C>();
	}
};

}

