#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Sandspear_Ambush

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Sandspear_Ambush.GE_Sandspear_Ambush_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_Sandspear_Ambush_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Sandspear_Ambush_C">();
	}
	static class UGE_Sandspear_Ambush_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Sandspear_Ambush_C>();
	}
};

}

