#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_TridentEngineEnergyConsumption_Default

#include "Basic.hpp"

#include "UWEAbilitySystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_TridentEngineEnergyConsumption_Default.GE_TridentEngineEnergyConsumption_Default_C
// 0x0000 (0x0C58 - 0x0C58)
class UGE_TridentEngineEnergyConsumption_Default_C final : public UUWEGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_TridentEngineEnergyConsumption_Default_C">();
	}
	static class UGE_TridentEngineEnergyConsumption_Default_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_TridentEngineEnergyConsumption_Default_C>();
	}
};

}

