#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: PLA_CoralTubeSmall_02c

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PLA_CoralTubeSmall_02c.PLA_CoralTubeSmall_02c_C
// 0x344A2CB0 (0x344A3000 - 0x0350)
class alignas(0x344A3000) APLA_CoralTubeSmall_02c_C final : public APackedLevelActor
{
public:
	class UInstancedStaticMeshComponent*          InstancedStaticMesh;                               // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PLA_CoralTubeSmall_02c_C">();
	}
	static class APLA_CoralTubeSmall_02c_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APLA_CoralTubeSmall_02c_C>();
	}
};

}

