#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SocketSubsystemEOS

#include "Basic.hpp"

#include "OnlineSubsystemUtils_classes.hpp"


namespace SDK
{

// Class SocketSubsystemEOS.NetDriverEOS
// 0x0008 (0x09B0 - 0x09A8)
class UNetDriverEOS : public UIpNetDriver
{
public:
	bool                                          bIsPassthrough;                                    // 0x09A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsUsingP2PSockets;                                // 0x09A9(0x0001)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9AA[0x6];                                      // 0x09AA(0x0006)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NetDriverEOS">();
	}
	static class UNetDriverEOS* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNetDriverEOS>();
	}
};

// Class SocketSubsystemEOS.NetDriverEOSBase
// 0x0000 (0x09B0 - 0x09B0)
class UNetDriverEOSBase final : public UNetDriverEOS
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NetDriverEOSBase">();
	}
	static class UNetDriverEOSBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNetDriverEOSBase>();
	}
};

// Class SocketSubsystemEOS.NetConnectionEOS
// 0x0010 (0x1EC0 - 0x1EB0)
class UNetConnectionEOS final : public UIpConnection
{
public:
	uint8                                         Pad_1EB0[0x10];                                    // 0x1EB0(0x0010)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NetConnectionEOS">();
	}
	static class UNetConnectionEOS* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNetConnectionEOS>();
	}
};

}

