#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: UWEAISpeaker

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "UWEChildActor_classes.hpp"


namespace SDK
{

// Class UWEAISpeaker.UWEAISpeakerComponent
// 0x0010 (0x00D0 - 0x00C0)
class UUWEAISpeakerComponent final : public UActorComponent
{
public:
	TArray<TWeakObjectPtr<class AUWESpeaker>>     Speakers;                                          // 0x00C0(0x0010)(ZeroConstructor, UObjectWrapper, NativeAccessSpecifierPrivate)

public:
	void PlaySound(class UFMODEvent* Event);
	void PlaySoundQueued(class UFMODEvent* Event);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UWEAISpeakerComponent">();
	}
	static class UUWEAISpeakerComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUWEAISpeakerComponent>();
	}
};

// Class UWEAISpeaker.UWESpeaker
// 0x0000 (0x02B8 - 0x02B8)
class AUWESpeaker final : public AUWEChildActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UWESpeaker">();
	}
	static class AUWESpeaker* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUWESpeaker>();
	}
};

}

