#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: UWECollision

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class UWECollision.UWECollisionProfile
// 0x0000 (0x0028 - 0x0028)
class UUWECollisionProfile final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UWECollisionProfile">();
	}
	static class UUWECollisionProfile* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUWECollisionProfile>();
	}
};

}

