#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: UWEPrototype

#include "Basic.hpp"

#include "UWEPrototype_classes.hpp"


namespace SDK
{

// Function UWEPrototype.UWEPrototypeActor.UpdateMaxSpeed
// (Final, Native, Private)

void AUWEPrototypeActor::UpdateMaxSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UWEPrototypeActor", "UpdateMaxSpeed");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

