#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: UWESequence

#include "Basic.hpp"

#include "LevelSequence_classes.hpp"


namespace SDK
{

// Class UWESequence.UWESerializedLevelSequenceActor
// 0x0018 (0x0370 - 0x0358)
class AUWESerializedLevelSequenceActor : public AReplicatedLevelSequenceActor
{
public:
	uint8                                         Pad_358[0x8];                                      // 0x0358(0x0008)(Fixing Size After Last Property [ Dumper-8 ])
	class UUWESaveComponent*                      SaveComponent;                                     // 0x0360(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	double                                        PlaybackTime;                                      // 0x0368(0x0008)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnLocalClientReady();
	void OnSequenceFinished();
	void OnSequencePlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UWESerializedLevelSequenceActor">();
	}
	static class AUWESerializedLevelSequenceActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUWESerializedLevelSequenceActor>();
	}
};

}

