#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: UWESteamDeck

#include "Basic.hpp"


namespace SDK::Params
{

// Function UWESteamDeck.UWESteamDeckFunctionLibrary.IsDeviceSteamDeck
// 0x0001 (0x0001 - 0x0000)
struct UWESteamDeckFunctionLibrary_IsDeviceSteamDeck final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

