#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: UWEXboxFSERuntime

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class UWEXboxFSERuntime.UWEXboxFSERuntimeSubsystem
// 0x0008 (0x0038 - 0x0030)
class UUWEXboxFSERuntimeSubsystem final : public ULocalPlayerSubsystem
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Struct Size After Last Property [ Dumper-8 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UWEXboxFSERuntimeSubsystem">();
	}
	static class UUWEXboxFSERuntimeSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUWEXboxFSERuntimeSubsystem>();
	}
};

}

