#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_HabitatBlightLabScreen

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_HabitatBlightLabScreen.WBP_HabitatBlightLabScreen_C.ExecuteUbergraph_WBP_HabitatBlightLabScreen
// 0x0008 (0x0008 - 0x0000)
struct WBP_HabitatBlightLabScreen_C_ExecuteUbergraph_WBP_HabitatBlightLabScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Powered;                        // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function WBP_HabitatBlightLabScreen.WBP_HabitatBlightLabScreen_C.SetPowered
// 0x0001 (0x0001 - 0x0000)
struct WBP_HabitatBlightLabScreen_C_SetPowered final
{
public:
	bool                                          Powered;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

