#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_DatabankEntryWrapper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_DatabankEntryWrapper.WBP_DatabankEntryWrapper_C
// 0x10D984C0 (0x10D98800 - 0x0340)
class alignas(0x10D98800) UWBP_DatabankEntryWrapper_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUWELazyWidget*                         Wrapper;                                           // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USN2DatabankEntryViewModel*             Entry_View_Model;                                  // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class UCommonButtonBase* Entry)> OnClicked;                        // 0x0358(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__WBP_DatabankEntryWrapper_Wrapper_K2Node_ComponentBoundEvent_1_OnWidgetInView__DelegateSignature();
	void Create_Widget();
	void ExecuteUbergraph_WBP_DatabankEntryWrapper(int32 EntryPoint);
	void Forward_On_Clicked(class UCommonButtonBase* Button);
	void Get_Widget(class UWBP_DatabankEntry_C** Widget);
	void GetDataAsset(class UUWEDatabankEntry** Entry);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_DatabankEntryWrapper_C">();
	}
	static class UWBP_DatabankEntryWrapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DatabankEntryWrapper_C>();
	}
};

}

