#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_PlayerIndicator_GoldFinderBiomod

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_PlayerIndicator_GoldFinderBiomod.WBP_PlayerIndicator_GoldFinderBiomod_C
// 0x10D984C0 (0x10D98800 - 0x0340)
class alignas(0x10D98800) UWBP_PlayerIndicator_GoldFinderBiomod_C final : public UUserWidget
{
public:
	class UImage*                                 Image_24;                                          // 0x0340(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_PlayerIndicator_GoldFinderBiomod_C">();
	}
	static class UWBP_PlayerIndicator_GoldFinderBiomod_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PlayerIndicator_GoldFinderBiomod_C>();
	}
};

}

