#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_NewsfeedImage

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_NewsfeedImage.WBP_NewsfeedImage_C
// 0x10D984C7 (0x10D9882F - 0x0368)
class alignas(0x10D9882F) UWBP_NewsfeedImage_C final : public UCommonUserWidget
{
public:
	class UImage*                                 Image;                                             // 0x0368(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_NewsfeedImage_C">();
	}
	static class UWBP_NewsfeedImage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NewsfeedImage_C>();
	}
};

}

