#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PDADialouge

#include "Basic.hpp"

#include "WBP_PDADialouge_classes.hpp"
#include "WBP_PDADialouge_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_PDADialouge.WBP_PDADialouge_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_PDADialouge_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.DelayedDeactivate
// (BlueprintCallable, BlueprintEvent)

void UWBP_PDADialouge_C::DelayedDeactivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "DelayedDeactivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.DialogueLineChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      NewLine                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_PDADialouge_C::DialogueLineChanged(const class FText& NewLine)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "DialogueLineChanged");

	Params::WBP_PDADialouge_C_DialogueLineChanged Parms{};

	Parms.NewLine = std::move(NewLine);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.ExecuteUbergraph_WBP_PDADialouge
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PDADialouge_C::ExecuteUbergraph_WBP_PDADialouge(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "ExecuteUbergraph_WBP_PDADialouge");

	Params::WBP_PDADialouge_C_ExecuteUbergraph_WBP_PDADialouge Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.FadeOut
// (Event, Public, BlueprintEvent)

void UWBP_PDADialouge_C::FadeOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "FadeOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.HandleSpeakerIconChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UTexture2D>        Icon                                                   (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_PDADialouge_C::HandleSpeakerIconChanged(TSoftObjectPtr<class UTexture2D> Icon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "HandleSpeakerIconChanged");

	Params::WBP_PDADialouge_C_HandleSpeakerIconChanged Parms{};

	Parms.Icon = Icon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.OnContextChanged
// (Event, Protected, BlueprintEvent)

void UWBP_PDADialouge_C::OnContextChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "OnContextChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.ResetPreAnimState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_PDADialouge_C::ResetPreAnimState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "ResetPreAnimState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.SetUWEDialogueViewModel
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUWEDialogueViewModel*            ViewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PDADialouge_C::SetUWEDialogueViewModel(class UUWEDialogueViewModel* ViewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "SetUWEDialogueViewModel");

	Params::WBP_PDADialouge_C_SetUWEDialogueViewModel Parms{};

	Parms.ViewModel = ViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.SimpleSubtitlesModeUpdated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Simple_                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PDADialouge_C::SimpleSubtitlesModeUpdated(bool Simple_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "SimpleSubtitlesModeUpdated");

	Params::WBP_PDADialouge_C_SimpleSubtitlesModeUpdated Parms{};

	Parms.Simple_ = Simple_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.SpeakerIconChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// TSoftObjectPtr<class UTexture2D>        NewIcon                                                (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UWBP_PDADialouge_C::SpeakerIconChanged(TSoftObjectPtr<class UTexture2D> NewIcon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "SpeakerIconChanged");

	Params::WBP_PDADialouge_C_SpeakerIconChanged Parms{};

	Parms.NewIcon = NewIcon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PDADialouge.WBP_PDADialouge_C.SpeakerNameChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      NewName                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_PDADialouge_C::SpeakerNameChanged(const class FText& NewName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PDADialouge_C", "SpeakerNameChanged");

	Params::WBP_PDADialouge_C_SpeakerNameChanged Parms{};

	Parms.NewName = std::move(NewName);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
