#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_StartScreen_Root

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UWECommonUI_classes.hpp"
#include "UWEFrontend_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_StartScreen_Root.WBP_StartScreen_Root_C
// 0x10D98348 (0x10D98800 - 0x04B8)
class alignas(0x10D98800) UWBP_StartScreen_Root_C final : public UFocusActivatableWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               RootPanel;                                         // 0x04C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUWEStartScreenViewModel*               UWEStartScreenViewModel;                           // 0x04C8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, DisableEditOnInstance, DuplicateTransient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCommonActivatableWidget*               Active_Screen_Widget;                              // 0x04D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnActivated();
	void Construct();
	void Destruct();
	void ExecuteUbergraph_WBP_StartScreen_Root(int32 EntryPoint);
	void ExitStartScreen();
	void GetScreenClassForState(EUWEStartScreenState InState, class UClass** ScreenClass);
	void InitializeViewModel();
	void OnActiveScreenDeactivated();
	void OnStartScreenStateChanged(EUWEStartScreenState NewState);
	void ShouldShowScreen(EUWEStartScreenState State, class UFocusActivatableWidget* Widget, bool* NeedToShow);
	void TryActivateScreenForState(EUWEStartScreenState InState, bool* Activated);

	class UWidget* BP_GetDesiredFocusTarget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_StartScreen_Root_C">();
	}
	static class UWBP_StartScreen_Root_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_StartScreen_Root_C>();
	}
};

}

