#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: WBP_NewsfeedRichText

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_NewsfeedRichText.WBP_NewsfeedRichText_C
// 0x10D98498 (0x10D98800 - 0x0368)
class alignas(0x10D98800) UWBP_NewsfeedRichText_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUWERichTextBlockWithLinks*             UWERichTextBlockWithLinks;                         // 0x0370(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              NewEventDispatcher;                                // 0x0378(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BndEvt__WBP_NewsfeedRichText_UWERichTextBlockWithLinks_K2Node_ComponentBoundEvent_0_OnLinkClicked__DelegateSignature(const class FString& Command, const class FString& Context);
	void ExecuteUbergraph_WBP_NewsfeedRichText(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_NewsfeedRichText_C">();
	}
	static class UWBP_NewsfeedRichText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NewsfeedRichText_C>();
	}
};

}

